version: "3.8"

services:
    frontend:
        image: node:18-slim
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - "1234:1234"
        command: sh -c "npm install && npm start"

    backend:
        build: .
        ports:
            - "5000:5000"
        restart: unless-stopped
        environment:
            - FLASK_ENV=development
            - PYTHONUNBUFFERED=1
        volumes:
            - ./server.py:/app/server.py
            - ./public:/app/public
        command: uv run server.py
