app = "webrtc-video-chat"
primary_region = "sjc" # Silicon Valley region - change as needed

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 500

[[http_service.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"]

[checks]
  [checks.health]
    port = 5000
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/"
    protocol = "http"